name: qfurniture
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state management
  stacked: ^2.2.7+1
  stacked_services: ^0.8.16
  flutter_hooks: ^0.18.2

  # ui
  google_fonts: ^2.2.0
  animations: ^2.0.2
  flutter_svg: ^1.0.0

dev_dependencies:
  stacked_generator: ^0.5.6
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

    
   


